### ISSUE TITLE
Input file for testing missing

### ISSUE THREAD

**Issue by zonca** [paesanilab/potential_fitting#12]
First issue found by automated testing!

`h2o_2.in` is missing from the folder:

    polynomial_generation/tests/2B

**Comment by ohamto** [comment]
@zonca Sorry for the delay. I had to make my origin repo public as well in order to push the `h2o_2.in` and now I can't make a pull request because it seems to have lost the fork to the upstream. In the meantime, here's the file with the extension changed for attachment.

[h2o_2.txt](https://github.com/paesanilab/potential_fitting/files/1265017/h2o_2.txt)

**Comment by zonca** [comment]
@ohamto yes, better rename your origin repo to `potential_fitting_stale`, then fork again and push to the fork

**Comment by ohamto** [comment]
@zonca Ok I've reforked it and I'm gonna create a pull request.

**Comment by ohamto** [comment]
#13 is ready to merge

**Comment by zonca** [comment]
thanks
